version: '3'

networks:
  default:

services:
  one-message-every-day:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: sethwrites-tmf-bot
    restart: unless-stopped
    networks:
      - default
    env_file:
      - .env